### ISSUE TITLE
How should the weight be used?

### ISSUE THREAD

**Issue by Xeoncross** [alixaxel/pagerank#2]
Reading through the [paper about WPR](http://people.cs.ksu.edu/~halmohri/files/weightedPageRank.pdf) it is hard to tell how you would decide to weight a given `graph.Link(n1, n2, ???)`. When should a node be given more weight?

**Comment by alixaxel** [comment]
That depends entirely on what you intend to use the PR for.

In classical web crawling, we could weight more or less a link, depending on the anchor text for instance.
